//
//  Countries.swift
//  COVIDtracker
//
//  Created by Prakhar Prakash Bhardwaj on 29/03/20.
//  Copyright © 2020 Prakhar Prakash Bhardwaj. All rights reserved.
//


public let countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "British Virgin Islands",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "CAR",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Caribbean Netherlands",
    "Cayman Islands",
    "Chad",
    "Channel Islands",
    "Chile",
    "China",
    "Colombia",
    "Congo",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Curaçao",
    "Cyprus",
    "Czechia",
    "DRC",
    "Denmark",
    "Diamond Princess",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Faeroe Islands",
    "Falkland Islands",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "MS Zaandam",
    "Macao",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nepal",
    "Netherlands",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Réunion",
    "S. Korea",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Martin",
    "Saint Pierre Miquelon",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Maarten",
    "Slovakia",
    "Slovenia",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "St. Barth",
    "St. Vincent Grenadines",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turks and Caicos",
    "UAE",
    "UK",
    "USA",
    "Uganda",
    "Ukraine",
    "Uruguay",
    "Uzbekistan",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Western Sahara",
    "World",
    "Yemen",
    "Zambia",
    "Zimbabwe",
    "Andaman and Nicobar Islands,India",
    "Arunachal Pradesh,India",
    "Andhra Pradesh,India",
    "Assam,India",
    "Bihar,India",
    "Chandigarh,India",
    "Chhattisgarh,India",
    "Dadra and Nagar Haveli,India",
    "Delhi,India",
    "Karnataka,India",
    "Kerala,India",
    "Goa,India",
    "Gujarat,India",
    "Haryana,India",
    "Himachal Pradesh,India",
    "Jammu and Kashmir,India",
    "Jharkhand,India",
    "Ladakh,India",
    "Lakshadweep,India",
    "Madhya Pradesh,India",
    "Maharashtra,India",
    "Manipur,India",
    "Meghalaya,India",
    "Mizoram,India",
    "Nagaland,India",
    "Odisha,India",
    "Puducherry,India",
    "Punjab,India",
    "Rajasthan,India",
    "Sikkim,India",
    "Tamil Nadu,India",
    "Telangana,India",
    "Tripura,India",
    "Uttarakhand,India",
    "Uttar Pradesh,India",
    "West Bengal,India",
    "Nicobars,Andaman and Nicobar Islands","North and Middle Andaman,Andaman and Nicobar Islands","South Andaman,Andaman and Nicobar Islands","Anantapur,Andhra Pradesh","Chittoor,Andhra Pradesh","East Godavari,Andhra Pradesh","Guntur,Andhra Pradesh","Krishna,Andhra Pradesh","Kurnool,Andhra Pradesh","Prakasam,Andhra Pradesh","S.P.S. Nellore,Andhra Pradesh","Srikakulam,Andhra Pradesh","Visakhapatnam,Andhra Pradesh","Vizianagaram,Andhra Pradesh","West Godavari,Andhra Pradesh","Y.S.R.,Andhra Pradesh","Anjaw,Arunachal Pradesh","Changlang,Arunachal Pradesh","East Kameng,Arunachal Pradesh","East Siang,Arunachal Pradesh","Kamle,Arunachal Pradesh","Kra Daadi,Arunachal Pradesh","Kurung Kumey,Arunachal Pradesh","Lepa Rada,Arunachal Pradesh","Lohit,Arunachal Pradesh","Longding,Arunachal Pradesh","Lower Dibang Valley,Arunachal Pradesh","Lower Siang,Arunachal Pradesh","Lower Subansiri,Arunachal Pradesh","Namsai,Arunachal Pradesh","Pakke Kessang,Arunachal Pradesh","Papum Pare,Arunachal Pradesh","Shi Yomi,Arunachal Pradesh","Siang,Arunachal Pradesh","Tawang,Arunachal Pradesh","Tirap,Arunachal Pradesh","Upper Dibang Valley,Arunachal Pradesh","Upper Siang,Arunachal Pradesh","Upper Subansiri,Arunachal Pradesh","West Kameng,Arunachal Pradesh","West Siang,Arunachal Pradesh","Baksa,Assam","Barpeta,Assam","Biswanath,Assam","Bongaigaon,Assam","Cachar,Assam","Charaideo,Assam","Chirang,Assam","Darrang,Assam","Dhemaji,Assam","Dhubri,Assam","Dibrugarh,Assam","Dima Hasao,Assam","Goalpara,Assam","Golaghat,Assam","Hailakandi,Assam","Hojai,Assam","Jorhat,Assam","Kamrup,Assam","Kamrup Metropolitan,Assam","Karbi Anglong,Assam","Karimganj,Assam","Kokrajhar,Assam","Lakhimpur,Assam","Majuli,Assam","Morigaon,Assam","Nagaon,Assam","Nalbari,Assam","Sivasagar,Assam","Sonitpur,Assam","South Salmara Mancachar,Assam","Tinsukia,Assam","Udalguri,Assam","West Karbi Anglong,Assam","Araria,Bihar","Arwal,Bihar","Aurangabad,Bihar","Banka,Bihar","Begusarai,Bihar","Bhagalpur,Bihar","Bhojpur,Bihar","Buxar,Bihar","Darbhanga,Bihar","Gaya,Bihar","Gopalganj,Bihar","Jamui,Bihar","Jehanabad,Bihar","Kaimur Bhabua,Bihar","Katihar,Bihar","Khagaria,Bihar","Kishanganj,Bihar","Lakhisarai,Bihar","Madhepura,Bihar","Madhubani,Bihar","Munger,Bihar","Muzaffarpur,Bihar","Nalanda,Bihar","Nawada,Bihar","West Champaran,Bihar","Patna,Bihar","East Champaran,Bihar","Purnia,Bihar","Rohtas,Bihar","Saharsa,Bihar","Samastipur,Bihar","Saran,Bihar","Sheikhpura,Bihar","Sheohar,Bihar","Sitamarhi,Bihar","Siwan,Bihar","Supaul,Bihar","Vaishali,Bihar","Chandigarh,Chandigarh","Balod,Chhattisgarh","Baloda Bazar,Chhattisgarh","Balrampur,Chhattisgarh","Bametara,Chhattisgarh","Bastar,Chhattisgarh","Bijapur,Chhattisgarh","Bilaspur,Chhattisgarh","Dakshin Bastar Dantewada,Chhattisgarh","Dhamtari,Chhattisgarh","Durg,Chhattisgarh","Gariaband,Chhattisgarh","Janjgir Champa,Chhattisgarh","Jashpur,Chhattisgarh","Kabeerdham,Chhattisgarh","Kondagaon,Chhattisgarh","Korba,Chhattisgarh","Koriya,Chhattisgarh","Mahasamund,Chhattisgarh","Mungeli,Chhattisgarh","Narayanpur,Chhattisgarh","Raigarh,Chhattisgarh","Raipur,Chhattisgarh","Rajnandgaon,Chhattisgarh","Sukma,Chhattisgarh","Surajpur,Chhattisgarh","Surguja,Chhattisgarh","Uttar Bastar Kanker,Chhattisgarh","Daman,Daman And Diu","Diu,Daman And Diu","Central Delhi,Delhi","East Delhi,Delhi","New Delhi,Delhi","North Delhi,Delhi","North East Delhi,Delhi","North West Delhi,Delhi","Shahdara,Delhi","South Delhi,Delhi","South East Delhi,Delhi","South West Delhi,Delhi","West Delhi,Delhi","North Goa,Goa","South Goa,Goa","Ahmadabad,Gujarat","Amreli,Gujarat","Anand,Gujarat","Aravalli,Gujarat","Banas Kantha,Gujarat","Bharuch,Gujarat","Bhavnagar,Gujarat","Botad,Gujarat","Chota Udaipur,Gujarat","Devbhumi Dwarka,Gujarat","Dohad,Gujarat","Gandhinagar,Gujarat","Gir Somnath,Gujarat","Jamnagar,Gujarat","Junagadh,Gujarat","Kachchh,Gujarat","Kheda,Gujarat","Mahesana,Gujarat","Mahisagar,Gujarat","Morbi,Gujarat","Narmada,Gujarat","Navsari,Gujarat","Panch Mahals,Gujarat","Patan,Gujarat","Porbandar,Gujarat","Rajkot,Gujarat","Sabar Kantha,Gujarat","Surat,Gujarat","Surendranagar,Gujarat","Tapi,Gujarat","The Dangs,Gujarat","Vadodara,Gujarat","Valsad,Gujarat","Ambala,Haryana","Bhiwani,Haryana","Charki Dadri,Haryana","Faridabad,Haryana","Fatehabad,Haryana","Gurugram,Haryana","Hisar,Haryana","Jhajjar,Haryana","Jind,Haryana","Kaithal,Haryana","Karnal,Haryana","Kurukshetra,Haryana","Mahendragarh,Haryana","Nuh,Haryana","Palwal,Haryana","Panchkula,Haryana","Panipat,Haryana","Rewari,Haryana","Rohtak,Haryana","Sirsa,Haryana","Sonipat,Haryana","Yamunanagar,Haryana","Bilaspur,Himachal Pradesh","Chamba,Himachal Pradesh","Hamirpur,Himachal Pradesh","Kangra,Himachal Pradesh","Kinnaur,Himachal Pradesh","Kullu,Himachal Pradesh","Lahul and Spiti,Himachal Pradesh","Mandi,Himachal Pradesh","Shimla,Himachal Pradesh","Sirmaur,Himachal Pradesh","Solan,Himachal Pradesh","Una,Himachal Pradesh","Anantnag,Jammu and Kashmir","Badgam,Jammu and Kashmir","Bandipore,Jammu and Kashmir","Baramula,Jammu and Kashmir","Doda,Jammu and Kashmir","Ganderbal,Jammu and Kashmir","Jammu,Jammu and Kashmir","Kathua,Jammu and Kashmir","Kishtwar,Jammu and Kashmir","Kulgam,Jammu and Kashmir","Kupwara,Jammu and Kashmir","Mirpur,Jammu and Kashmir","Muzaffarabad,Jammu and Kashmir","Pulwama,Jammu and Kashmir","Punch,Jammu and Kashmir","Rajouri,Jammu and Kashmir","Ramban,Jammu and Kashmir","Reasi,Jammu and Kashmir","Samba,Jammu and Kashmir","Shupiyan,Jammu and Kashmir","Srinagar,Jammu and Kashmir","Udhampur,Jammu and Kashmir","Bokaro,Jharkhand","Chatra,Jharkhand","Deoghar,Jharkhand","Dhanbad,Jharkhand","Dumka,Jharkhand","Garhwa,Jharkhand","Giridih,Jharkhand","Godda,Jharkhand","Gumla,Jharkhand","Hazaribagh,Jharkhand","Jamtara,Jharkhand","Khunti,Jharkhand","Kodarma,Jharkhand","Latehar,Jharkhand","Lohardaga,Jharkhand","Pakur,Jharkhand","Palamu,Jharkhand","Pashchimi Singhbhum,Jharkhand","Purbi Singhbhum,Jharkhand","Ramgarh,Jharkhand","Ranchi,Jharkhand","Sahibganj,Jharkhand","Saraikela-Kharsawan,Jharkhand","Simdega,Jharkhand","Bagalkote,Karnataka","Ballari,Karnataka","Belagavi,Karnataka","Bengaluru,Karnataka","Bengaluru Rural,Karnataka","Bidar,Karnataka","Chamarajanagara,Karnataka","Chikkaballapura,Karnataka","Chikkamagaluru,Karnataka","Chitradurga,Karnataka","Dakshina Kannada,Karnataka","Davanagere,Karnataka","Dharwad,Karnataka","Gadag,Karnataka","Hassan,Karnataka","Haveri,Karnataka","Kalaburagi,Karnataka,Gulbarga","Kodagu,Karnataka","Kolar,Karnataka","Koppal,Karnataka","Mandya,Karnataka","Mysuru,Karnataka","Raichur,Karnataka","Ramanagara,Karnataka","Shivamogga,Karnataka,Shimoga","Tumakuru,Karnataka","Udupi,Karnataka","Uttara Kannada,Karnataka","Vijayapura,Karnataka","Yadgir,Karnataka","Alappuzha,Kerala","Ernakulam,Kerala","Idukki,Kerala","Kannur,Kerala","Kasaragod,Kerala","Kollam,Kerala","Kottayam,Kerala","Kozhikode,Kerala","Malappuram,Kerala","Palakkad,Kerala","Pathanamthitta,Kerala","Thiruvananthapuram,Kerala","Thrissur,Kerala","Wayanad,Kerala","Kargil,Ladakh","Leh,Ladakh","Agar Malwa,Madhya Pradesh","Alirajpur,Madhya Pradesh","Anuppur,Madhya Pradesh","Ashoknagar,Madhya Pradesh","Balaghat,Madhya Pradesh","Barwani,Madhya Pradesh","Betul,Madhya Pradesh","Bhind,Madhya Pradesh","Bhopal,Madhya Pradesh","Burhanpur,Madhya Pradesh","Chhatarpur,Madhya Pradesh","Chhindwara,Madhya Pradesh","Damoh,Madhya Pradesh","Datia,Madhya Pradesh","Dewas,Madhya Pradesh","Dhar,Madhya Pradesh","Dindori,Madhya Pradesh","Khandwa,Madhya Pradesh","Guna,Madhya Pradesh","Gwalior,Madhya Pradesh","Harda,Madhya Pradesh","Hoshangabad,Madhya Pradesh","Indore,Madhya Pradesh","Jabalpur,Madhya Pradesh","Jhabua,Madhya Pradesh","Katni,Madhya Pradesh","Mandla,Madhya Pradesh","Mandsaur,Madhya Pradesh","Morena,Madhya Pradesh","Narsimhapur,Madhya Pradesh","Neemuch,Madhya Pradesh","Niwari,Madhya Pradesh","Panna,Madhya Pradesh","Raisen,Madhya Pradesh","Rajgarh,Madhya Pradesh","Ratlam,Madhya Pradesh","Rewa,Madhya Pradesh","Sagar,Madhya Pradesh","Satna,Madhya Pradesh","Sehore,Madhya Pradesh","Seoni,Madhya Pradesh","Shahdol,Madhya Pradesh","Shajapur,Madhya Pradesh","Sheopur,Madhya Pradesh","Shivpuri,Madhya Pradesh","Sidhi,Madhya Pradesh","Singrauli,Madhya Pradesh","Tikamgarh,Madhya Pradesh","Ujjain,Madhya Pradesh","Umaria,Madhya Pradesh","Vidisha,Madhya Pradesh","Khargone,Madhya Pradesh","Ahmadnagar,Maharashtra","Akola,Maharashtra","Amravati,Maharashtra","Aurangabad,Maharashtra","Bhandara,Maharashtra","Bid,Maharashtra","Buldana,Maharashtra","Chandrapur,Maharashtra","Dhule,Maharashtra","Gadchiroli,Maharashtra","Gondiya,Maharashtra","Hingoli,Maharashtra","Jalgaon,Maharashtra","Jalna,Maharashtra","Kolhapur,Maharashtra","Latur,Maharashtra","Mumbai,Maharashtra","Mumbai Suburban,Maharashtra","Nagpur,Maharashtra","Nanded,Maharashtra","Nandurbar,Maharashtra","Nashik,Maharashtra","Osmanabad,Maharashtra","Palghar,Maharashtra","Parbhani,Maharashtra","Pune,Maharashtra","Raigarh,Maharashtra","Ratnagiri,Maharashtra","Sangli,Maharashtra","Satara,Maharashtra","Sindhudurg,Maharashtra","Solapur,Maharashtra","Thane,Maharashtra","Wardha,Maharashtra","Washim,Maharashtra","Yavatmal,Maharashtra","Bishnupur,Manipur","Chandel,Manipur","Churachandpur,Manipur","Imphal East,Manipur","Imphal West,Manipur","Jiribam,Manipur","Kakching,Manipur","Kamjong,Manipur","Kangpokpi,Manipur","Noney,Manipur","Pherzawl,Manipur","Senapati,Manipur","Tamenglong,Manipur","Tengnoupal,Manipur","Thoubal,Manipur","Ukhrul,Manipur","East Garo Hills,Meghalaya","East Jaintia Hills,Meghalaya","East Khasi Hills,Meghalaya","North Garo Hills,Meghalaya","Ribhoi,Meghalaya","South Garo Hills,Meghalaya","South West Garo Hills,Meghalaya","South West Khasi Hills,Meghalaya","West Garo Hills,Meghalaya","West Jaintia Hills,Meghalaya","West Khasi Hills,Meghalaya","Aizawl,Mizoram","Champhai,Mizoram","Kolasib,Mizoram","Lawngtlai,Mizoram","Lunglei,Mizoram","Mamit,Mizoram","Saiha,Mizoram","Serchhip,Mizoram","Dimapur,Nagaland","Kiphire,Nagaland","Kohima,Nagaland","Longleng,Nagaland","Mokokchung,Nagaland","Mon,Nagaland","Peren,Nagaland","Phek,Nagaland","Tuensang,Nagaland","Wokha,Nagaland","Zunheboto,Nagaland","Anugul,Odisha","Balangir,Odisha","Baleshwar,Odisha","Bargarh,Odisha","Baudh,Odisha","Bhadrak,Odisha","Cuttack,Odisha","Debagarh,Odisha","Dhenkanal,Odisha","Gajapati,Odisha","Ganjam,Odisha","Jagatsinghapur,Odisha","Jajapur,Odisha","Jharsuguda,Odisha","Kalahandi,Odisha","Kandhamal,Odisha","Kendrapara,Odisha","Kendujhar,Odisha","Khordha,Odisha","Koraput,Odisha","Malkangiri,Odisha","Mayurbhanj,Odisha","Nabarangapur,Odisha","Nayagarh,Odisha","Nuapada,Odisha","Puri,Odisha","Rayagada,Odisha","Sambalpur,Odisha","Subarnapur,Odisha","Sundargarh,Odisha","Karaikal,Puducherry","Mahe,Puducherry","Puducherry,Puducherry","Yanam,Puducherry","Amritsar,Punjab","Barnala,Punjab","Bathinda,Punjab","Faridkot,Punjab","Fatehgarh Sahib,Punjab","Fazilka,Punjab","Firozpur,Punjab","Gurdaspur,Punjab","Hoshiarpur,Punjab","Jalandhar,Punjab","Kapurthala,Punjab","Ludhiana,Punjab","Mansa,Punjab","Moga,Punjab","Pathankot,Punjab","Patiala,Punjab","Rupnagar,Punjab","S.A.S. Nagar,Punjab,Mohali","Sangrur,Punjab","Shahid Bhagat Singh Nagar,Punjab","Sri Muktsar Sahib,Punjab","Tarn Taran,Punjab","Ajmer,Rajasthan","Alwar,Rajasthan","Banswara,Rajasthan","Baran,Rajasthan","Barmer,Rajasthan","Bharatpur,Rajasthan","Bhilwara,Rajasthan","Bikaner,Rajasthan","Bundi,Rajasthan","Chittaurgarh,Rajasthan","Churu,Rajasthan","Dausa,Rajasthan","Dhaulpur,Rajasthan","Dungarpur,Rajasthan","Ganganagar,Rajasthan","Hanumangarh,Rajasthan","Jaipur,Rajasthan","Jaisalmer,Rajasthan","Jalore,Rajasthan","Jhalawar,Rajasthan","Jhunjhunu,Rajasthan","Jodhpur,Rajasthan","Karauli,Rajasthan","Kota,Rajasthan","Nagaur,Rajasthan","Pali,Rajasthan","Pratapgarh,Rajasthan","Rajsamand,Rajasthan","Sawai Madhopur,Rajasthan","Sikar,Rajasthan","Sirohi,Rajasthan","Tonk,Rajasthan","Udaipur,Rajasthan","East District,Sikkim","North District,Sikkim","South District,Sikkim","West District,Sikkim","Ariyalur,Tamil Nadu","Chennai,Tamil Nadu","Coimbatore,Tamil Nadu","Cuddalore,Tamil Nadu","Dharmapuri,Tamil Nadu","Dindigul,Tamil Nadu","Erode,Tamil Nadu","Kancheepuram,Tamil Nadu","Kanniyakumari,Tamil Nadu","Karur,Tamil Nadu","Krishnagiri,Tamil Nadu","Madurai,Tamil Nadu","Nagapattinam,Tamil Nadu","Namakkal,Tamil Nadu","Perambalur,Tamil Nadu","Pudukkottai,Tamil Nadu","Ramanathapuram,Tamil Nadu","Salem,Tamil Nadu","Sivaganga,Tamil Nadu","Thanjavur,Tamil Nadu","The Nilgiris,Tamil Nadu","Theni,Tamil Nadu","Thiruvallur,Tamil Nadu","Thiruvarur,Tamil Nadu","Thoothukkudi,Tamil Nadu","Tiruchirappalli,Tamil Nadu","Tirunelveli,Tamil Nadu","Tiruppur,Tamil Nadu","Tiruvannamalai,Tamil Nadu","Vellore,Tamil Nadu","Viluppuram,Tamil Nadu","Virudhunagar,Tamil Nadu","Adilabad,Telangana","Bhadradri Kothagudem,Telangana","Hyderabad,Telangana","Jagitial,Telangana","Jangoan,Telangana","Jayashankar,Telangana","Jogulamba Gadwal,Telangana","Kamareddy,Telangana","Karimnagar,Telangana","Khammam,Telangana","Kumuram Bheem Asifabad,Telangana","Mahabubabad,Telangana","Mahabubnagar,Telangana","Mancherial,Telangana","Medak,Telangana","Medchal Malkajgiri,Telangana","Mulugu,Telangana","Nagarkurnool,Telangana","Nalgonda,Telangana","Narayanpet,Telangana","Nirmal,Telangana","Nizamabad,Telangana","Peddapalli,Telangana","Rajanna Sircilla,Telangana","Ranga Reddy,Telangana","Sangareddy,Telangana","Siddipet,Telangana","Suryapet,Telangana","Vikarabad,Telangana","Wanaparthy,Telangana","Warangal Rural,Telangana","Warangal Urban,Telangana","Yadadri Bhuvanagiri,Telangana","Dhalai,Tripura","Gomati,Tripura","Khowai,Tripura","North Tripura,Tripura","Sipahijala,Tripura","South Tripura,Tripura","Unokoti,Tripura","West Tripura,Tripura","Agra,Uttar Pradesh","Aligarh,Uttar Pradesh","Ambedkar Nagar,Uttar Pradesh","Amethi,Uttar Pradesh","Amroha,Uttar Pradesh","Auraiya,Uttar Pradesh","Azamgarh,Uttar Pradesh","Baghpat,Uttar Pradesh","Bahraich,Uttar Pradesh","Ballia,Uttar Pradesh","Balrampur,Uttar Pradesh","Banda,Uttar Pradesh","Bara Banki,Uttar Pradesh","Bareilly,Uttar Pradesh","Basti,Uttar Pradesh","Bhadohi,Uttar Pradesh","Bijnor,Uttar Pradesh","Budaun,Uttar Pradesh","Bulandshahr,Uttar Pradesh","Chandauli,Uttar Pradesh","Chitrakoot,Uttar Pradesh","Deoria,Uttar Pradesh","Etah,Uttar Pradesh","Etawah,Uttar Pradesh","Faizabad,Uttar Pradesh","Farrukhabad,Uttar Pradesh","Fatehpur,Uttar Pradesh","Firozabad,Uttar Pradesh","Gautam Buddha Nagar,Uttar Pradesh,Noida","Ghaziabad,Uttar Pradesh","Ghazipur,Uttar Pradesh","Gonda,Uttar Pradesh","Gorakhpur,Uttar Pradesh","Hamirpur,Uttar Pradesh","Hapur,Uttar Pradesh","Hardoi,Uttar Pradesh","Hathras,Uttar Pradesh","Jalaun,Uttar Pradesh","Jaunpur,Uttar Pradesh","Jhansi,Uttar Pradesh","Kannauj,Uttar Pradesh","Kanpur Dehat,Uttar Pradesh","Kanpur Nagar,Uttar Pradesh","Kasganj,Uttar Pradesh","Kaushambi,Uttar Pradesh","Kheri,Uttar Pradesh","Kushinagar,Uttar Pradesh","Lalitpur,Uttar Pradesh","Lucknow,Uttar Pradesh","Mahoba,Uttar Pradesh","Mahrajganj,Uttar Pradesh","Mainpuri,Uttar Pradesh","Mathura,Uttar Pradesh","Mau,Uttar Pradesh","Meerut,Uttar Pradesh","Mirzapur,Uttar Pradesh","Moradabad,Uttar Pradesh","Muzaffarnagar,Uttar Pradesh","Pilibhit,Uttar Pradesh","Pratapgarh,Uttar Pradesh","Prayagraj,Uttar Pradesh","Rae Bareli,Uttar Pradesh","Rampur,Uttar Pradesh","Saharanpur,Uttar Pradesh","Sambhal,Uttar Pradesh","Sant Kabir Nagar,Uttar Pradesh","Shahjahanpur,Uttar Pradesh","Shamli,Uttar Pradesh","Shrawasti,Uttar Pradesh","Siddharthnagar,Uttar Pradesh","Sitapur,Uttar Pradesh","Sonbhadra,Uttar Pradesh","Sultanpur,Uttar Pradesh","Unnao,Uttar Pradesh","Varanasi,Uttar Pradesh","Almora,Uttarakhand","Bageshwar,Uttarakhand","Chamoli,Uttarakhand","Champawat,Uttarakhand","Dehradun,Uttarakhand","Haridwar,Uttarakhand","Nainital,Uttarakhand","Pauri Garhwal,Uttarakhand","Pithoragarh,Uttarakhand","Rudraprayag,Uttarakhand","Tehri Garhwal,Uttarakhand","Udham Singh Nagar,Uttarakhand","Uttarkashi,Uttarakhand","Alipurduar,West Bengal","Bankura,West Bengal","Birbhum,West Bengal","Cooch Behar,West Bengal","Dakshin Dinajpur,West Bengal","Darjeeling,West Bengal","Hooghly,West Bengal","Howrah,West Bengal","Jalpaiguri,West Bengal","Jhargram,West Bengal","Kalimpong,West Bengal","Kolkata,West Bengal","Maldah,West Bengal","Medinipur West,West Bengal","Murshidabad,West Bengal","Nadia,West Bengal","North 24 Parganas,West Bengal","Paschim Bardhaman,West Bengal","Purba Bardhaman,West Bengal","Medinipur East,West Bengal","Purulia,West Bengal","South 24 Parganas,West Bengal","Uttar Dinajpur,West Bengal","Tenkasi,Tamil Nadu","Chengalpattu,Tamil Nadu","Ranipet,Tamil Nadu","Kallakurichi,Tamil Nadu","Tirupathur,Tamil Nadu"
]
